# action.yml
name: 'call OB Farm to run task'
description: ''
inputs:
  pipeline_id:
    description: 'pipeline_id'
    required: true
  project:
    description: 'project'
    required: true
  timeout:
    description: 'timeout'
    required: false
    default: '4800'
  jobname:
    description: 'jobname'
    required: false
    default: 'farm'
outputs:
  success:
    description: 'the status for the task'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pipeline_id }}
    - ${{ inputs.project }}
    - ${{ inputs.timeout }}
    - ${{ inputs.jobname }}