# configuration meta
# - category options: user, organization, system
# - type options: string, integer, decimal, boolean, list
- id: 1
  category: 'user'
  config_key: 'odc.sqlexecute.default.mysqlAutoCommitMode'
  type: 'string'
  max_value: ~
  min_value: ~
  allowed_values: 'ON,OFF'
  default_value: 'ON'
  is_nullable: false
  description: ''
- id: 2
  category: 'user'
  config_key: 'odc.sqlexecute.default.mysqlAutoCommitMode'
  type: 'string'
  max_value: ~
  min_value: ~
  allowed_values: 'ON,OFF'
  default_value: 'OFF'
  is_nullable: false
  description: ''
- id: 3
  category: 'user'
  config_key: 'odc.sqlexecute.default.queryLimit'
  type: 'integer'
  max_value: 1
  min_value: 100000
  allowed_values: ~
  default_value: '1000'
  is_nullable: false
  description: ''
- id: 4
  category: 'user'
  config_key: 'odc.sqlexecute.default.fetchColumnInfo'
  type: 'boolean'
  max_value: ~
  min_value: ~
  allowed_values: 'true,false'
  default_value: 'true'
  is_nullable: false
  description: ''
- id: 5
  category: 'user'
  config_key: 'odc.sqlexecute.default.delimiter'
  type: 'string'
  max_value: ~
  min_value: ~
  allowed_values: ~
  default_value: ';'
  is_nullable: false
  description: ''
