drop materialized view if exists test_mv_auto_refresh;
drop materialized view if exists test_mv_never;
drop materialized view if exists test_mv_force;
drop materialized view if exists test_mv_fast;
drop materialized view if exists test_mv_complete;
drop materialized view if exists test_mv_each_column;
drop materialized view if exists test_mv_query_rewrite;
drop materialized view if exists test_mv_computation;
drop materialized view if exists test_mv_all_syntax;
drop materialized view log on test_mv_base;
drop table if exists test_mv_base;