name: 🌟 Enhancement
description: Provide details for a feature in development
labels: [enhancement, type-feature]
title: "[Enhancement]: "
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
