CREATE TABLE TRIGGER_TABLE (col varchar2(20))
/

CREATE OR REPLACE TRIGGER TRIGGER_ACCESSOR
    BEFORE INSERT OR DELETE OR UPDATE ON TRIGGER_TABLE
    FOR EACH ROW
    BEGIN
        DBMS_OUTPUT.PUT_LINE('db-browser test');
    END;
/

CREATE OR REPLACE TRIGGER TRIGGER_INVALID_ACCESSOR
    BEFORE INSERT ON TRIGGER_TABLE
    FOR EACH ROW
    BEGIN
        select 1+1 from invalid_dual;
    END;