CREATE OR REPLACE PACKAGE PAC_ACCESSOR IS
    v1 number;
    type cur_emp is ref cursor;
	PROCEDURE PROC_PARAMS_ACCESSOR (p_in IN NUMBER DEFAULT 100, p_in_out IN OUT VARCHAR2, p_out OUT DATE, p_result OUT BOOLEAN);
	FUNCTION FUNC_DETAIL_ACCESSOR (p_in IN NUMBER, p_in_out IN OUT VARCHAR2, p_out OUT DATE) RETURN NUMBER;
	FUNCTION FUNC_IN_PRO RETURN NUMBER;
END PAC_ACCESSOR;
/

CREATE OR REPLACE PACKAGE BODY PAC_ACCESSOR AS
    PROCEDURE PROC_PARAMS_ACCESSOR (p_in IN NUMBER DEFAULT 100, p_in_out IN OUT VARCHAR2, p_out OUT DATE, p_result OUT BOOLEAN) IS
        total NUMBER;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('db-browser test');
    END;

    FUNCTION FUNC_DETAIL_ACCESSOR (p_in IN NUMBER, p_in_out IN OUT VARCHAR2, p_out OUT DATE)
    RETURN NUMBER IS
        total NUMBER;
    BEGIN
        RETURN total;
    END;

    FUNCTION FUNC_IN_PRO
    RETURN NUMBER IS
        total NUMBER;
    BEGIN
        RETURN total;
    END;
END PAC_ACCESSOR;
/

CREATE OR REPLACE PACKAGE PAC_INVALID_ACCESSOR IS
    PROCEDURE my_procedure;
    FUNCTION my_function RETURN NUMBER;
END PAC_INVALID_ACCESSOR;
/

CREATE OR REPLACE PACKAGE BODY PAC_INVALID_ACCESSOR IS
    PROCEDURE my_procedure IS
    BEGIN
        -- 无效的语句
        SELECT * FROM non_existent_table;
    END my_procedure;

    FUNCTION my_function RETURN NUMBER IS
    BEGIN
        -- 无效的语句
        SELECT * FROM non_existent_table;
    END my_function;
END PAC_INVALID_ACCESSOR;