CREATE TABLE IF NOT EXISTS `spring_session` (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	PRIMARY KEY (PRIMARY_ID),
	KEY `SPRING_SESSION_IX1`(SESSION_ID),
	KEY `SPRING_SESSION_IX2`(EXPIRY_TIME),
	KEY `SPRING_SESSION_IX3`(PRINCIPAL_NAME)
);

CREATE TABLE IF NOT EXISTS `spring_session_attributes` (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);