CREATE OR REPLACE PACKAGE BODY dbms_xa AS

  FUNCTION XA_START(xid IN DBMS_XA_XID, flag IN PLS_INTEGER) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_START);

  FUNCTION XA_END(xid IN DBMS_XA_XID, flag IN PLS_INTEGER) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_END);

  FUNCTION XA_PREPARE(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_PREPARE);

  FUNCTION XA_COMMIT(xid IN DBMS_XA_XID, onePhase IN BOOLEAN) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_COMMIT);

  FUNCTION XA_FORGET(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_FORGET);

  FUNCTION XA_GETLASTOER RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_GETLASTOER);

  FUNCTION XA_RECOVER RETURN DBMS_XA_XID_ARRAY;
  PRAGMA INTERFACE(C, INNER_XA_RECOVER);

  FUNCTION XA_ROLLBACK(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_ROLLBACK);

  FUNCTION XA_SETTIMEOUT(seconds IN PLS_INTEGER) RETURN PLS_INTEGER;
  PRAGMA INTERFACE(C, INNER_XA_SETTIMEOUT);

  PROCEDURE DIST_TXN_SYNC;
  PRAGMA INTERFACE(C, INNER_DIST_TXN_SYNC);

END dbms_xa;
