CREATE OR replace PACKAGE BODY dbms_warning AS
PROCEDURE ADD_WARNING_SETTING_CAT(WARNING_CATEGORY IN VARCHAR2, WARNING_VALUE IN VARCHAR2, SCOPE IN VARCHAR2);
pragma interface (C, WARNING_ADD_CAT);

PROCEDURE ADD_WARNING_SETTING_NUM(WARNING_NUMBER IN PLS_INTEGER, WARNING_VALUE  IN VARCHAR2, SCOPE IN VARCHAR2);
pragma interface (C, WARNING_ADD_NUM);

FUNCTION GET_WARNING_SETTING_CAT(WARNING_CATEGORY IN VARCHAR2) RETURN VARCHAR2;
pragma interface (C, WARNING_GET_SETTING_CAT);

FUNCTION GET_WARNING_SETTING_NUM(WARNING_NUMBER IN PLS_INTEGER) RETURN VARCHAR2;
pragma interface (C, WARNING_GET_SETTING_NUM);

FUNCTION GET_WARNING_SETTING_STRING RETURN VARCHAR2;
pragma interface (C, WARNING_GET_SETTING_STR);

PROCEDURE SET_WARNING_SETTING_STRING(VALUE IN VARCHAR2, SCOPE IN VARCHAR2);
pragma interface (C, WARNING_SET);

FUNCTION GET_CATEGORY(WARNING_NUMBER IN PLS_INTEGER) RETURN VARCHAR2;
pragma interface (C, WARNING_GET_CAT);
END dbms_warning;
//