CREATE OR REPLACE PACKAGE dbms_xa AS
  TMNOFLAGS CONSTANT PLS_INTEGER := 0;
  TMSUCCESS CONSTANT PLS_INTEGER := 67108864; --UTL_RAW.CAST_TO_BINARY_INTEGER('04000000');
  TMJOIN CONSTANT PLS_INTEGER := 2097152; --UTL_RAW.CAST_TO_BINARY_INTEGER('00200000');
  TMSUSPEND CONSTANT PLS_INTEGER := 33554432; --UTL_RAW.CAST_TO_BINARY_INTEGER('02000000');
  TMRESUME CONSTANT PLS_INTEGER := 134217728; --UTL_RAW.CAST_TO_BINARY_INTEGER('08000000');

  XA_RBBASE CONSTANT PLS_INTEGER := 100;
  XA_RBROLLBACK CONSTANT PLS_INTEGER := XA_RBBASE;
  XA_RBCOMMFAIL CONSTANT PLS_INTEGER := XA_RBBASE + 1;
  XA_RBDEADLOCK CONSTANT PLS_INTEGER := XA_RBBASE + 2;
  XA_RBINTEGRITY CONSTANT PLS_INTEGER := XA_RBBASE + 3;
  XA_RBOTHER CONSTANT PLS_INTEGER := XA_RBBASE + 4;
  XA_RBPROTO CONSTANT PLS_INTEGER := XA_RBBASE + 5;
  XA_RBTIMEOUT CONSTANT PLS_INTEGER := XA_RBBASE + 6;
  XA_RBTRANSIENT CONSTANT PLS_INTEGER := XA_RBBASE + 7;
  XA_RBEND CONSTANT PLS_INTEGER := XA_RBTRANSIENT;
  XA_NOMIGRATE CONSTANT PLS_INTEGER := 9;
  XA_HEURHAZ CONSTANT PLS_INTEGER := 8;
  XA_HEURCOM CONSTANT PLS_INTEGER := 7;
  XA_HEURRB CONSTANT PLS_INTEGER := 6;
  XA_HEURMIX CONSTANT PLS_INTEGER := 5;
  XA_RETRY CONSTANT PLS_INTEGER := 4;
  XA_RDONLY CONSTANT PLS_INTEGER := 3;
  XA_OK CONSTANT PLS_INTEGER := 0;
  XAER_ASYNC CONSTANT PLS_INTEGER := -2;
  XAER_RMERR CONSTANT PLS_INTEGER := -3;
  XAER_NOTA CONSTANT PLS_INTEGER := -4;
  XAER_INVAL CONSTANT PLS_INTEGER := -5;
  XAER_PROTO CONSTANT PLS_INTEGER := -6;
  XAER_RMFAIL CONSTANT PLS_INTEGER := -7;
  XAER_DUPID CONSTANT PLS_INTEGER := -8;
  XAER_OUTSIDE CONSTANT PLS_INTEGER := -9;

  FUNCTION XA_START(xid IN DBMS_XA_XID, flag IN PLS_INTEGER) RETURN PLS_INTEGER;

  FUNCTION XA_END(xid IN DBMS_XA_XID, flag IN PLS_INTEGER) RETURN PLS_INTEGER;

  FUNCTION XA_PREPARE(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;

  FUNCTION XA_COMMIT(xid IN DBMS_XA_XID, onePhase IN BOOLEAN) RETURN PLS_INTEGER;

  FUNCTION XA_FORGET(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;

  FUNCTION XA_GETLASTOER RETURN PLS_INTEGER;

  FUNCTION XA_RECOVER RETURN DBMS_XA_XID_ARRAY;

  FUNCTION XA_ROLLBACK(xid IN DBMS_XA_XID) RETURN PLS_INTEGER;

  FUNCTION XA_SETTIMEOUT(seconds IN PLS_INTEGER) RETURN PLS_INTEGER;

  PROCEDURE DIST_TXN_SYNC;

END dbms_xa;
