CREATE OR REPLACE PACKAGE BODY UTL_ENCODE IS
  FUNCTION BASE64_ENCODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, BASE64_ENCODE);
  FUNCTION BASE64_DECODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, BASE64_DECODE);
END;
//
