CREATE OR REPLACE PROCEDURE DROPIFEXISTS_MVIEW(new_mview IN VARCHAR2)
IS
    v_count NUMBER(10);
BEGIN
SELECT count(*)
INTO v_count
FROM USER_MVIEWS
WHERE MVIEW_NAME = UPPER(new_mview);
IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || new_mview || ' CASCADE CONSTRAINTS';
END IF;
END;
/

call DROPIFEXISTS_MVIEW('MV_HASH_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_HASH_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_LIST_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_LIST_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_RANGE_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_RANGE_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_RANGE_MULTIPLE_RANGE');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_HASH_MULTIPLE_LIST');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_HASH_MULTIPLE_HASH');
call DROPIFEXISTS_MVIEW('MV_SINGLE_RANGE_MULTIPLE_RANGE');
call DROPIFEXISTS_MVIEW('MV_SINGLE_HASH_MULTIPLE_LIST');
call DROPIFEXISTS_MVIEW('MV_SINGLE_LIST_MULTIPLE_HASH');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_RANGE_SINGLE_RANGE');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_HASH_SINGLE_LIST');
call DROPIFEXISTS_MVIEW('MV_T_SINGLE_HASH_SINGLE_HASH');
call DROPIFEXISTS_MVIEW('MV_SINGLE_RANGE_SINGLE_RANGE');
call DROPIFEXISTS_MVIEW('MV_SINGLE_HASH_SINGLE_LIST');
call DROPIFEXISTS_MVIEW('MV_SINGLE_LIST_SINGLE_HASH');