CREATE OR REPLACE PROCEDURE DROPIFEXISTS_TABLE(new_table IN varchar2)
    IS
    v_count number(10);
BEGIN
    SELECT count(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = upper(new_table);
    IF v_count > 0
    THEN
        EXECUTE IMMEDIATE 'drop table ' || new_table || ' purge';
    END IF;
END;
/

call DROPIFEXISTS_TABLE('HASH_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('HASH_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('LIST_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('LIST_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('RANGE_PART_SINGLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('RANGE_PART_MULTIPLE_KEY_BY_PARSER');
call DROPIFEXISTS_TABLE('CONSTRAINT_MULTY_BY_PARSER');
call DROPIFEXISTS_TABLE('CONSTRAINT_PRIMARY_BY_PARSER');
call DROPIFEXISTS_TABLE('TEST_INDEX_BY_PARSER');
call DROPIFEXISTS_TABLE('T_SINGLE_RANGE_MULTIPLE_RANGE');
call DROPIFEXISTS_TABLE('T_SINGLE_HASH_MULTIPLE_LIST');
call DROPIFEXISTS_TABLE('T_SINGLE_HASH_MULTIPLE_HASH');
call DROPIFEXISTS_TABLE('SINGLE_RANGE_MULTIPLE_RANGE');
call DROPIFEXISTS_TABLE('SINGLE_HASH_MULTIPLE_LIST');
call DROPIFEXISTS_TABLE('SINGLE_LIST_MULTIPLE_HASH');
call DROPIFEXISTS_TABLE('T_SINGLE_RANGE_SINGLE_RANGE');
call DROPIFEXISTS_TABLE('T_SINGLE_HASH_SINGLE_LIST');
call DROPIFEXISTS_TABLE('T_SINGLE_HASH_SINGLE_HASH');
call DROPIFEXISTS_TABLE('SINGLE_RANGE_SINGLE_RANGE');
call DROPIFEXISTS_TABLE('SINGLE_HASH_SINGLE_LIST');
call DROPIFEXISTS_TABLE('SINGLE_LIST_SINGLE_HASH');