CREATE MATERIALIZED VIEW MV_HASH_PART_SINGLE_KEY_BY_PARSER
  partition by hash(col1)
                (partition P0,
                partition P1,
                partition P2,
                partition P3,
                partition P4,
                partition P5)
  as select * from HASH_PART_SINGLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_HASH_PART_MULTIPLE_KEY_BY_PARSER
  PARTITION BY HASH(COL1,COL2) PARTITIONS 10
       as select * from HASH_PART_MULTIPLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_LIST_PART_SINGLE_KEY_BY_PARSER
  partition by list(log_value)
                (partition P01 values  ('A','B','C'),
                partition P02 values  ('D','E','F'),
                partition P03 values  ('G','H','I'),
                partition P04 values  (DEFAULT))
       as select * from LIST_PART_SINGLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_LIST_PART_MULTIPLE_KEY_BY_PARSER
  PARTITION BY LIST(COL2,COL3)
        (PARTITION "P0" VALUES  ((1,1),(3,3)),
         PARTITION "P1" VALUES  ((4,4),(7,7)),
         PARTITION "P2" VALUES  ((8,8),(9,9))
        ) as select * from LIST_PART_MULTIPLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_RANGE_PART_SINGLE_KEY_BY_PARSER
  partition by range(log_date)
                (partition M202001 values less than (TO_DATE('2020-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')),
                partition M202002 values less than (TO_DATE('2020-03-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS','NLS_CALENDAR=GREGORIAN')),
                partition M202003 values less than (TO_DATE('2020-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS','NLS_CALENDAR=GREGORIAN')),
                partition MMAX values less than (MAXVALUE))
       as select * from RANGE_PART_SINGLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_RANGE_PART_MULTIPLE_KEY_BY_PARSER
  PARTITION BY RANGE(COL1,COL2)
        (PARTITION M202001 VALUES LESS THAN(1,1)
         , PARTITION M202002 VALUES LESS THAN(3,3)
         , PARTITION M202003 VALUES LESS THAN(5,5)
         , PARTITION MMAX VALUES LESS THAN (MAXVALUE,MAXVALUE)
         ) as select * from RANGE_PART_MULTIPLE_KEY_BY_PARSER;

CREATE MATERIALIZED VIEW MV_T_SINGLE_RANGE_MULTIPLE_RANGE
  PARTITION BY RANGE(COL1)
       SUBPARTITION BY RANGE(COL2,COL3)
       SUBPARTITION TEMPLATE
         (SUBPARTITION MP0 VALUES LESS THAN(2020,2020),
          SUBPARTITION MP1 VALUES LESS THAN(2021,2021),
          SUBPARTITION MP2 VALUES LESS THAN(2022,2022)
          )
         (PARTITION P0 VALUES LESS THAN(100),
          PARTITION P1 VALUES LESS THAN(200)
          ) as select * from  T_SINGLE_RANGE_MULTIPLE_RANGE;

CREATE MATERIALIZED VIEW MV_T_SINGLE_HASH_MULTIPLE_LIST
  PARTITION BY HASH(COL1)
       SUBPARTITION BY LIST(COL2,COL3)
       SUBPARTITION TEMPLATE
        (SUBPARTITION SP0 VALUES(100,100),
         SUBPARTITION SP1 VALUES(200,200),
         SUBPARTITION SP2 VALUES(300,300)
         )
        PARTITIONS 5
       as select * from T_SINGLE_HASH_MULTIPLE_LIST;

CREATE MATERIALIZED VIEW MV_T_SINGLE_HASH_MULTIPLE_HASH
  PARTITION BY HASH(COL1)
       SUBPARTITION BY HASH(COL2,COL3)
        SUBPARTITIONS 3
        PARTITIONS 5
       as select * from T_SINGLE_HASH_MULTIPLE_HASH;

CREATE MATERIALIZED VIEW MV_SINGLE_RANGE_MULTIPLE_RANGE
  PARTITION BY RANGE(COL1)
       SUBPARTITION BY RANGE(COL2,COL3)
        (PARTITION P0 VALUES LESS THAN(100)
          (SUBPARTITION SP0 VALUES LESS THAN(2020,2020),
           SUBPARTITION SP1 VALUES LESS THAN(2021,2021)
          ),
         PARTITION P1 VALUES LESS THAN(200)
          (SUBPARTITION SP2 VALUES LESS THAN(2020,2020),
           SUBPARTITION SP3 VALUES LESS THAN(2021,2021),
           SUBPARTITION SP4 VALUES LESS THAN(2022,2022)
           )
         ) as select * from SINGLE_RANGE_MULTIPLE_RANGE;

CREATE MATERIALIZED VIEW MV_SINGLE_HASH_MULTIPLE_LIST
  PARTITION BY HASH(COL1)
       SUBPARTITION BY LIST(COL2,COL3)
        (PARTITION P0
          (SUBPARTITION SP0 VALUES((1,1),(3,3)),
           SUBPARTITION SP1 VALUES((4,4),(7,7))
          ),
         PARTITION P1
          (SUBPARTITION SP2 VALUES((1,1),(3,3)),
           SUBPARTITION SP3 VALUES((4,4),(7,7)),
           SUBPARTITION SP4 VALUES((8,8),(9,9))
           )
        ) as select * from SINGLE_HASH_MULTIPLE_LIST;

CREATE MATERIALIZED VIEW MV_SINGLE_LIST_MULTIPLE_HASH
  PARTITION BY LIST(COL1)
       SUBPARTITION BY HASH(COL2,COL3)
       (PARTITION P0 VALUES('01')
         (SUBPARTITION SP0,
          SUBPARTITION SP1
          ),
        PARTITION P1 VALUES('02')
         (SUBPARTITION SP2,
          SUBPARTITION SP3,
          SUBPARTITION SP4
          )
        ) as select * from SINGLE_LIST_MULTIPLE_HASH;

CREATE MATERIALIZED VIEW MV_T_SINGLE_RANGE_SINGLE_RANGE
  PARTITION BY RANGE(COL1)
       SUBPARTITION BY RANGE(COL2)
       SUBPARTITION TEMPLATE
         (SUBPARTITION MP0 VALUES LESS THAN(2020),
          SUBPARTITION MP1 VALUES LESS THAN(2021),
          SUBPARTITION MP2 VALUES LESS THAN(2022)
          )
         (PARTITION P0 VALUES LESS THAN(100),
          PARTITION P1 VALUES LESS THAN(200)
          ) as select * from T_SINGLE_RANGE_SINGLE_RANGE;

CREATE MATERIALIZED VIEW MV_T_SINGLE_HASH_SINGLE_LIST
  PARTITION BY HASH(COL1)
       SUBPARTITION BY LIST(COL2)
       SUBPARTITION TEMPLATE
        (SUBPARTITION SP0 VALUES(100),
         SUBPARTITION SP1 VALUES(200),
         SUBPARTITION SP2 VALUES(300)
         )
        PARTITIONS 5
       as select * from T_SINGLE_HASH_SINGLE_LIST;

CREATE MATERIALIZED VIEW MV_T_SINGLE_HASH_SINGLE_HASH
  PARTITION BY HASH(COL1)
       SUBPARTITION BY HASH(COL2)
        SUBPARTITIONS 3
        PARTITIONS 5
       as select * from T_SINGLE_HASH_SINGLE_HASH;

CREATE MATERIALIZED VIEW MV_SINGLE_RANGE_SINGLE_RANGE
  PARTITION BY RANGE(COL1)
       SUBPARTITION BY RANGE(COL2)
        (PARTITION P0 VALUES LESS THAN(100)
          (SUBPARTITION SP0 VALUES LESS THAN(2020),
           SUBPARTITION SP1 VALUES LESS THAN(2021)
          ),
         PARTITION P1 VALUES LESS THAN(200)
          (SUBPARTITION SP2 VALUES LESS THAN(2020),
           SUBPARTITION SP3 VALUES LESS THAN(2021),
           SUBPARTITION SP4 VALUES LESS THAN(2022)
           )
         ) as select * from SINGLE_RANGE_SINGLE_RANGE;

CREATE MATERIALIZED VIEW MV_SINGLE_HASH_SINGLE_LIST
  PARTITION BY HASH(COL1)
       SUBPARTITION BY LIST(COL2)
        (PARTITION P0
          (SUBPARTITION SP0 VALUES(1,3),
           SUBPARTITION SP1 VALUES(4,7)
          ),
         PARTITION P1
          (SUBPARTITION SP2 VALUES(1,3),
           SUBPARTITION SP3 VALUES(4,7)
           )
        ) as select * from SINGLE_HASH_SINGLE_LIST;

CREATE MATERIALIZED VIEW MV_SINGLE_LIST_SINGLE_HASH
  PARTITION BY LIST(COL1)
       SUBPARTITION BY HASH(COL2)
       (PARTITION P0 VALUES('01')
         (SUBPARTITION SP0,
          SUBPARTITION SP1
          ),
        PARTITION P1 VALUES('02')
         (SUBPARTITION SP2,
          SUBPARTITION SP3,
          SUBPARTITION SP4
          )
        ) as select * from SINGLE_LIST_SINGLE_HASH;
