CREATE OR REPLACE PROCEDURE DROPIFEXISTS_MVIEW_LOG(new_mview_log IN VARCHAR2)
IS
    v_count NUMBER(10);
BEGIN
SELECT count(*)
INTO v_count
FROM USER_MVIEW_LOGS
WHERE LOG_TABLE = UPPER('MLOG$_' || new_mview_log);
IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW LOG ON ' || new_mview_log;
END IF;
END;
/

CALL DROPIFEXISTS_MVIEW_LOG('TEST_MVLOG_PARALLEL');
CALL DROPIFEXISTS_MVIEW_LOG('TEST_MVLOG_ENABLE_AUTO_PURGE');
CALL DROPIFEXISTS_MVIEW_LOG('TEST_MVLOG_DISABLE_AUTO_PURGE');
call DROPIFEXISTS_TABLE('TEST_MVLOG_PARALLEL');
call DROPIFEXISTS_TABLE('TEST_MVLOG_ENABLE_AUTO_PURGE');
call DROPIFEXISTS_TABLE('TEST_MVLOG_DISABLE_AUTO_PURGE');
