CREATE OR REPLACE PROCEDURE DROPIFEXISTS_MVIEW_LOG(new_mview_log IN VARCHAR2)
IS
    v_count NUMBER(10);
BEGIN
SELECT count(*)
INTO v_count
FROM USER_MVIEW_LOGS
WHERE LOG_TABLE = UPPER('MLOG$_' || new_mview_log);
IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW LOG ON ' || new_mview_log;
END IF;
END;
/


CREATE OR REPLACE PROCEDURE DROPIFEXISTS_MVIEW(new_mview IN VARCHAR2)
IS
    v_count NUMBER(10);
BEGIN
SELECT count(*)
INTO v_count
FROM USER_MVIEWS
WHERE MVIEW_NAME = UPPER(new_mview);
IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || new_mview || ' CASCADE CONSTRAINTS';
END IF;
END;
/

CREATE OR REPLACE PROCEDURE DROPIFEXISTS_TABLE(new_table IN varchar2)
    IS
    v_count number(10);
BEGIN
SELECT count(*)
INTO v_count
FROM user_tables
WHERE table_name = upper(new_table);
IF v_count > 0
    THEN
        EXECUTE IMMEDIATE 'drop table ' || new_table || ' cascade constraints purge';
END IF;
END;
/

CALL DROPIFEXISTS_MVIEW('TEST_MV_ALLSYNTAX');
CALL DROPIFEXISTS_MVIEW('TEST_MV_COMPUTATION');
CALL DROPIFEXISTS_MVIEW('TEST_MV_QUERYREWRITE');
CALL DROPIFEXISTS_MVIEW('TEST_MV_EACHCOLUMN');
CALL DROPIFEXISTS_MVIEW('TEST_MV_COMPLETE');
CALL DROPIFEXISTS_MVIEW('TEST_MV_FAST');
CALL DROPIFEXISTS_MVIEW('TEST_MV_FORCE');
CALL DROPIFEXISTS_MVIEW('TEST_MV_NEVER');
CALL DROPIFEXISTS_MVIEW('TEST_MV_AUTOREFRESH');
CALL DROPIFEXISTS_MVIEW_LOG('TEST_MV_BASE');
CALL DROPIFEXISTS_TABLE('TEST_MV_BASE');