CREATE TABLE TEST_MV_BASE (
                            COL1 INT PRIMARY KEY,
                            COL2 INT,
                            COL3 INT,
                            COL4 INT
);

CREATE MATERIALIZED VIEW LOG ON TEST_MV_BASE
  WITH SEQUENCE (COL2, COL3,COL4) INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW TEST_MV_ALLSYNTAX (
    PRIMARY KEY (PRIM)
)
PARALLEL 5
PARTITION BY HASH (PRIM)
WITH COLUMN GROUP (ALL COLUMNS, EACH COLUMN)
REFRESH COMPLETE
ON DEMAND
START WITH CURRENT_DATE
NEXT CURRENT_DATE + INTERVAL '1' HOUR
DISABLE QUERY REWRITE
DISABLE ON QUERY COMPUTATION AS
SELECT COL1 AS PRIM, COL2 AS COL2, COL3 AS COL3, COL4 AS COL4 FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_COMPUTATION REFRESH COMPLETE ENABLE ON QUERY COMPUTATION AS
SELECT COL1, COUNT(*) AS CNT
FROM TEST_MV_BASE
GROUP BY COL1;

CREATE MATERIALIZED VIEW TEST_MV_QUERYREWRITE NEVER REFRESH ENABLE QUERY REWRITE AS
SELECT * FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_EACHCOLUMN WITH COLUMN GROUP(EACH COLUMN) AS
SELECT * FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_COMPLETE REFRESH COMPLETE AS
SELECT * FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_FAST
REFRESH FAST AS
SELECT COL1, COUNT(*) AS COUNT_COL
FROM TEST_MV_BASE
GROUP BY COL1;

CREATE MATERIALIZED VIEW TEST_MV_FORCE REFRESH FORCE AS
SELECT * FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_NEVER NEVER REFRESH  AS
SELECT * FROM TEST_MV_BASE;

CREATE MATERIALIZED VIEW TEST_MV_AUTOREFRESH REFRESH COMPLETE START WITH CURRENT_DATE NEXT CURRENT_DATE + INTERVAL '1' DAY AS
SELECT * FROM TEST_MV_BASE;