kind: resource
version: v2
templates:
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 1
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.sqlexecute.default.queryLimit"
        data_type: java.lang.String
      - column_name: value
        value: "1000"
        data_type: java.lang.String
      - column_name: description
        value: "SQL query row limit in team organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 2
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.sqlexecute.default.queryCount"
        data_type: java.lang.String
      - column_name: value
        value: "1000"
        data_type: java.lang.String
      - column_name: description
        value: "SQL query row limit default value in team organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 3
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.task.default.rollbackPlanEnabled"
        data_type: java.lang.String
      - column_name: value
        value: "false"
        data_type: java.lang.String
      - column_name: description
        value: "Automatic generate rollback plan for database changes in team organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 4
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.task.default.taskDescriptionPrompt"
        data_type: java.lang.String
      - column_name: value
        value: ""
        data_type: java.lang.String
      - column_name: description
        value: "Task description field prompt text in team organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 5
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.task.default.importTaskStructureReplacementEnabled"
        data_type: java.lang.String
      - column_name: value
        value: "true"
        data_type: java.lang.String
      - column_name: description
        value: "Whether to replace the task structure when importing tasks in team organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
