kind: resource
version: v2
templates:
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 100
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.sqlexecute.default.queryLimit"
        data_type: java.lang.String
      - column_name: value
        value: "1000"
        data_type: java.lang.String
      - column_name: label
        value: "individual"
        data_type: java.lang.String
      - column_name: description
        value: "SQL query row limit in individual organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 101
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.sqlexecute.default.queryCount"
        data_type: java.lang.String
      - column_name: value
        value: "1000"
        data_type: java.lang.String
      - column_name: label
        value: "individual"
        data_type: java.lang.String
      - column_name: description
        value: "SQL query row limit value in individual organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
  - metadata:
      allow_duplicate: false
      table_name: config_organization_configuration
      unique_keys: ["organization_id", "key"]
    specs:
      - column_name: id
        default_value: 102
        data_type: java.lang.Long
      - column_name: organization_id
        value: ${ORGANIZATION_ID}
        data_type: java.lang.Long
      - column_name: key
        value: "odc.task.default.rollbackPlan"
        data_type: java.lang.String
      - column_name: value
        value: "false"
        data_type: java.lang.String
      - column_name: label
        value: "individual"
        data_type: java.lang.String
      - column_name: description
        value: "Automatic generate rollback plan for database changes in individual organization."
        data_type: java.lang.String
      - column_name: creator_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long
      - column_name: last_modifier_id
        value: ${CREATOR_ID}
        data_type: java.lang.Long