CREATE TABLE IF NOT EXISTS `collaboration_worksheet` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `organization_id` bigint NOT NULL COMMENT 'record organization ID',
  `project_id` bigint NOT NULL COMMENT 'project id, FK refer to collaboration_project.id',
  `workspace_id` bigint NOT NULL COMMENT 'workspace id, FK refer to workspace.id',
  `creator_id` bigint NOT NULL COMMENT 'creator id，FK refer to iam_user.id',
  `path` varchar(1024) NOT NULL COMMENT 'fully qualified path of worksheet',
  `path_level` int NOT NULL COMMENT 'the number of levels in path',
  `object_id` varchar(1024) DEFAULT NULL COMMENT 'objectName of cloud object storage,or id of local object storage',
  `extension` varchar(64) DEFAULT NULL COMMENT 'worksheet extension',
  `size` bigint DEFAULT NULL COMMENT 'The total size of the file, measured in bytes',
  `version` bigint NOT NULL DEFAULT 0 COMMENT 'edit version,for edit conflict check',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collaboration_worksheet_organization_id_project_id_workspace_id_path` (`organization_id`,`project_id`,`workspace_id`,`path`),
  UNIQUE KEY `uk_collaboration_worksheet_object_id` (`object_id`),
  KEY `idx_collaboration_worksheet_organization_id_project_id_workspace_id_update_time` (`organization_id`,`project_id`,`workspace_id`,`update_time`),
  KEY `idx_collaboration_worksheet_organization_id_project_id_workspace_id_path_level_path` (`organization_id`,`project_id`,`workspace_id`,`path_level`,`path`)
) COMMENT = 'worksheet for project';